name: Video Games With Filters
favicon: null
layout_spectrum: 0.9155302646104246
typography_spectrum: 0.5847342873457819
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.06411784840747714
  lightness: 0.7808811247814447
  saturation: 0.8285368992947042
  rhythmicContrast: 0.7952611537184566
purpose: []
